name: CI-CD Pipeline

on:
  push:
    branches: ["develop"]

jobs:

  # 🔨 BUILD JOB
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🔨 Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t devops-demo .

      - name: 📦 Save Docker Image
        run: docker save devops-demo -o devops-demo.tar

      - name: ⬆️ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: devops-demo.tar


  # 🧪 TEST JOB
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: ⬇️ Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: 📦 Load Docker Image
        run: docker load -i devops-demo.tar

      - name: 🧪 Test Container
        run: |
          echo "Testing container..."

          docker run -d -p 8080:80 --name test-container devops-demo

          echo "Waiting for container to start..."
          sleep 10

          echo "Checking response..."
          curl -v http://localhost:8080

          echo "Validating content..."
          curl http://localhost:8080 | grep "Hello"

          docker rm -f test-container


  # 🚀 DEPLOY JOB
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: 🚀 Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            set -x

            echo "Connected to EC2"

            cd /home/ec2-user

            rm -rf demo-app

            echo "Cloning repo..."
            GIT_ASKPASS=true git clone https://github.com/vivekarote-dev/demo-app.git

            cd demo-app

            echo "Stopping old container..."
            sudo docker rm -f nginx-container || true

            echo "Building new image..."
            sudo docker build -t nginx-devops-demo .

            echo "Starting new container..."
            sudo docker run -d -p 80:80 --name nginx-container nginx-devops-demo

            sudo docker ps -a
